version: '3.8'

services:
  person-web-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/SpringBootCrudService/person/welcome"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s